using EbaDpm.Converter.Core.Access.Dpm20;
using EbaDpm.Converter.Tests.Schema;
using Microsoft.Data.Sqlite;

namespace EbaDpm.Converter.Tests.Dpm2;

/// <summary>
/// <c>mTable</c>, <c>mTaxonomyTable</c> and <c>mTemplateOrTable</c> -- the DPM 2.0 template tree.
/// It reuses <see cref="Dpm20SkeletonFixture"/> (collection <c>Dpm2Skeleton</c>): the same
/// <c>--all</c> conversion already loads the complete structure
/// (<see cref="EbaDpm.Converter.Core.Mapping.Dpm20.Dpm20StructureLoader"/> always runs, without a
/// separate flag), so the 755 MB Access database does not need to be re-read for this.
///
/// The matches against the source are by CODE (109/563/788); what is emitted, and what is checked
/// here, are ROWS (111/572/847). The figures were verified beforehand against the real .db
/// generated by the CLI before writing each assertion (nothing is assumed without measuring).
///
/// The ROWS are 847: the pair <c>(if 4.2, C_34.02.b)</c> is emitted because a module composition
/// declared <c>C_34.02.b</c> as an ABSTRACT table and the closure that does not resolve abstract
/// tables used to lose it. This is the gap that <see cref="Dpm20AxisAndCellTests"/> used to
/// document. No assertion was ever relaxed, only the new correct value re-measured.
/// </summary>
[Collection("Dpm2Skeleton")]
[Trait("Tier", "RealData")]
public sealed class Dpm20StructureLoaderTests(Dpm20SkeletonFixture fixture)
{
    // ------------------------------------------------------------------
    // 1 - ROW counts: 847 / 847 / 1,530 = 111 + 572 + 847
    // ------------------------------------------------------------------

    [DataFact]
    public void MTable_Has847Rows() => Assert.Equal(847, CountRows("mTable"));

    [DataFact]
    public void MTaxonomyTable_Has847Rows() => Assert.Equal(847, CountRows("mTaxonomyTable"));

    [DataFact]
    public void MTemplateOrTable_Has1530Rows_111Group_572Template_847Table()
    {
        Assert.Equal(1530, CountRows("mTemplateOrTable"));
        Assert.Equal(111, ScalarLong("SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup' AND \"Level\" = 1"));
        Assert.Equal(572, ScalarLong("SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup' AND \"Level\" = 2"));
        Assert.Equal(847, ScalarLong("SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable'"));
    }

    // ------------------------------------------------------------------
    // 2 - The invariant that looks at no reference: mTaxonomyTable and the BusinessTable rows of
    // mTemplateOrTable are the SAME set of (TaxonomyID, TableID) pairs. The loader already checks it
    // at run time (PairInvariantHolds); this test checks it for real, by querying the written .db
    // rather than trusting the flag the loader itself computed.
    // ------------------------------------------------------------------

    [DataFact]
    public void MTaxonomyTable_And_BusinessTable_AreTheSamePairSet_847Equal()
    {
        var taxonomyTablePairs = ReadPairs(
            "SELECT \"TaxonomyID\", \"TableID\" FROM \"mTaxonomyTable\"");
        var businessTablePairs = ReadPairs(
            "SELECT \"TaxonomyID\", \"TemplateOrTableID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable'");

        // 847, not 846: see the class comment.
        Assert.Equal(847, taxonomyTablePairs.Count);
        Assert.Equal(847, businessTablePairs.Count);

        var onlyInTaxonomyTable = taxonomyTablePairs.Except(businessTablePairs).ToList();
        var onlyInBusinessTable = businessTablePairs.Except(taxonomyTablePairs).ToList();

        Assert.True(
            onlyInTaxonomyTable.Count == 0 && onlyInBusinessTable.Count == 0,
            $"The sets are NOT identical: {onlyInTaxonomyTable.Count} pairs only in mTaxonomyTable "
            + $"({string.Join(", ", onlyInTaxonomyTable.Take(10))}), {onlyInBusinessTable.Count} only in "
            + $"mTemplateOrTable/BusinessTable ({string.Join(", ", onlyInBusinessTable.Take(10))}).");
    }

    /// <summary><c>mTaxonomyTable.AnnotatedTableID = TableID</c> in all 847 rows, without a single exception.</summary>
    [DataFact]
    public void MTaxonomyTable_AnnotatedTableID_EqualsTableID_In847Rows()
    {
        Assert.Equal(847, CountRows("mTaxonomyTable"));
        var mismatches = ScalarLong("SELECT COUNT(*) FROM \"mTaxonomyTable\" WHERE \"AnnotatedTableID\" <> \"TableID\"");
        Assert.Equal(0, mismatches);
    }

    /// <summary>
    /// <c>Order</c> is contiguous <c>0..n-1</c>, with no gaps or duplicates, WITHIN EACH GROUP OF
    /// SIBLINGS WITH A REAL PARENT (<c>ParentTemplateOrTableID &lt;&gt; 0</c>). It covers at once the
    /// 572 template nodes under their group and the 799 <c>BusinessTable</c> rows under their
    /// template (see the test named below). The groups with <c>Parent = 0</c> (the root and the 48
    /// orphans) are deliberately NOT included: they follow their own rule, checked separately.
    /// </summary>
    [DataFact]
    public void Order_IsContiguous0ToNMinus1_WithinEachSiblingGroupWithARealParent()
    {
        var rows = ReadTriples(
            "SELECT \"ParentTemplateOrTableID\", \"Order\", \"TemplateOrTableCode\" "
            + "FROM \"mTemplateOrTable\" WHERE \"ParentTemplateOrTableID\" <> 0");

        Assert.True(rows.Count > 0, "There are no rows with a real parent; nothing to check (unexpected).");

        var nonDense = new List<string>();
        foreach (var group in rows.GroupBy(r => r.A))
        {
            var orders = group.Select(r => r.B).OrderBy(o => o).ToList();
            var expected = Enumerable.Range(0, orders.Count).ToList();
            if (!orders.SequenceEqual(expected))
            {
                nonDense.Add($"ParentID={group.Key}: Order=[{string.Join(",", orders)}], expected 0..{orders.Count - 1}");
            }
        }

        Assert.True(
            nonDense.Count == 0,
            $"{nonDense.Count} sibling groups with a real parent and a non-dense Order 0..N-1. Examples: "
            + string.Join(" | ", nonDense.Take(10)));
    }

    // ------------------------------------------------------------------
    // 3 - The tree: three strata, Level is not depth, root/orphans with a literal Parent = 0.
    // ------------------------------------------------------------------

    /// <summary>
    /// <c>Level</c> is NOT the depth of the tree: a <c>BusinessTable</c> is <c>Level</c> 1 and hangs
    /// from a <c>Level</c> 2 node. It checks the invariant in ALL rows with a real parent (799 of
    /// 847; the pair <c>(if 4.2, C_34.02.b)</c> hangs from a real parent), not just the witness case
    /// -- a test that "fixed" this by expecting the parent to be Level 0 would be wrong.
    /// </summary>
    [DataFact]
    public void BusinessTable_IsLevel1_AndItsRealParentIsLevel2()
    {
        var rows = ReadIntTriples(
            """
            SELECT bt."TemplateOrTableID", bt."Level", parent."Level"
            FROM "mTemplateOrTable" bt
            JOIN "mTemplateOrTable" parent ON parent."TemplateOrTableID" = bt."ParentTemplateOrTableID"
            WHERE bt."TemplateOrTableType" = 'BusinessTable' AND bt."ParentTemplateOrTableID" <> 0
            """);

        Assert.Equal(799, rows.Count);

        var wrong = rows.Where(r => r.B != 1 || r.C != 2).ToList();
        Assert.True(
            wrong.Count == 0,
            $"{wrong.Count} BusinessTable rows with a real parent do not satisfy (Level=1, parent.Level=2). "
            + $"Examples (TemplateOrTableID, Level, parent.Level): {string.Join(", ", wrong.Take(10))}");
    }

    /// <summary>
    /// The root -- and, here, the orphan as well -- carries <c>ParentTemplateOrTableID = 0</c>, NEVER
    /// <c>NULL</c> (this is not universal across the other mappings). It is checked explicitly, in
    /// the three populations that could carry 0: the 111 L1 groups, the 48 orphans and, for
    /// completeness, that the whole column is never NULL in any of the 1,529 rows.
    /// </summary>
    [DataFact]
    public void Root_And_Orphans_CarryParentEqualTo0_NeverNull()
    {
        Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"ParentTemplateOrTableID\" IS NULL"));

        var rootParents = ReadIntColumn(
            "SELECT \"ParentTemplateOrTableID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup' AND \"Level\" = 1");
        Assert.Equal(111, rootParents.Count);
        Assert.All(rootParents, p => Assert.Equal(0, p));

        var orphanParents = ReadIntColumn(
            "SELECT \"ParentTemplateOrTableID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"ParentTemplateOrTableID\" = 0");
        Assert.Equal(48, orphanParents.Count);
        Assert.All(orphanParents, p => Assert.Equal(0, p));

        // Confirms with type literalness: the column is an integer, and the value read is the
        // integer 0 (not an empty string or another DBNull in disguise) -- through a typed read.
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText =
            "SELECT \"ParentTemplateOrTableID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup' AND \"Level\" = 1 LIMIT 1";
        using var reader = command.ExecuteReader();
        Assert.True(reader.Read());
        Assert.False(reader.IsDBNull(0), "ParentTemplateOrTableID of the root is DBNull; it must be the integer 0.");
        Assert.Equal(0, reader.GetInt32(0));
    }

    /// <summary>The 683 <c>TableGroup</c> nodes carry <c>eba_tg</c> in front; the 847 <c>BusinessTable</c> rows, none.</summary>
    [DataFact]
    public void TableGroup_CarriesEbaTgPrefix_BusinessTable_Never()
    {
        Assert.Equal(683, ScalarLong("SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup'"));

        var groupsWithoutPrefix = ScalarLong(
            "SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup' AND \"TemplateOrTableCode\" NOT LIKE 'eba_tg%'");
        Assert.Equal(0, groupsWithoutPrefix);

        var tablesWithPrefix = ScalarLong(
            "SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"TemplateOrTableCode\" LIKE 'eba_tg%'");
        Assert.Equal(0, tablesWithPrefix);
    }

    /// <summary>
    /// Witness case: the template of a table is its <c>AbstractTableID</c>, or the table itself.
    /// <c>C_02.00.a</c> and <c>C_02.00.b</c> hang from <c>eba_tgC_02.00</c>, which is the abstract
    /// <c>C_02.00</c>. Measured in the real .db: TemplateOrTableID 59 (C_02.00.a) and 178
    /// (C_02.00.b), both with ParentTemplateOrTableID = 884, which is eba_tgC_02.00.
    /// </summary>
    [DataFact]
    public void WitnessCase_C0200a_And_C0200b_HangFromEbaTgC0200()
    {
        var parentCodeOfA = ScalarString(
            "SELECT parent.\"TemplateOrTableCode\" FROM \"mTemplateOrTable\" bt "
            + "JOIN \"mTemplateOrTable\" parent ON parent.\"TemplateOrTableID\" = bt.\"ParentTemplateOrTableID\" "
            + "WHERE bt.\"TemplateOrTableCode\" = 'C_02.00.a' AND bt.\"TemplateOrTableType\" = 'BusinessTable' AND bt.\"ParentTemplateOrTableID\" <> 0");
        var parentCodeOfB = ScalarString(
            "SELECT parent.\"TemplateOrTableCode\" FROM \"mTemplateOrTable\" bt "
            + "JOIN \"mTemplateOrTable\" parent ON parent.\"TemplateOrTableID\" = bt.\"ParentTemplateOrTableID\" "
            + "WHERE bt.\"TemplateOrTableCode\" = 'C_02.00.b' AND bt.\"TemplateOrTableType\" = 'BusinessTable' AND bt.\"ParentTemplateOrTableID\" <> 0");

        Assert.Equal("eba_tgC_02.00", parentCodeOfA);
        Assert.Equal("eba_tgC_02.00", parentCodeOfB);
    }

    /// <summary>
    /// <c>Order</c> follows NATURAL order, never alphabetical: <c>C_09.04</c> &lt; <c>C_10.00</c>
    /// &lt; <c>C_11.00</c> within the SAME parent. Alphabetically "C_10.00" would come before
    /// "C_09.04" (the character '1' is less than '9'); the correct natural order puts them the other
    /// way round. Measured in the real .db: the three are template nodes
    /// (eba_tgC_09.04/eba_tgC_10.00/eba_tgC_11.00), same parent (TemplateOrTableID 899), with Order
    /// 11/12/15.
    /// </summary>
    [DataFact]
    public void Order_IsNatural_NotAlphabetical_C0904BeforeC1000BeforeC1100()
    {
        var rows = ReadCodeParentOrder(["eba_tgC_09.04", "eba_tgC_10.00", "eba_tgC_11.00"]);

        Assert.Equal(3, rows.Count);
        var parents = rows.Select(r => r.ParentId).Distinct().ToList();
        Assert.True(parents.Count == 1, $"The three witness codes do not share a parent: {string.Join(",", parents)}.");

        var orderByCode = rows.ToDictionary(r => r.Code, r => r.Order, StringComparer.Ordinal);
        Assert.True(orderByCode["eba_tgC_09.04"] < orderByCode["eba_tgC_10.00"]);
        Assert.True(orderByCode["eba_tgC_10.00"] < orderByCode["eba_tgC_11.00"]);
    }

    /// <summary>
    /// The tree only exists in the 4.2 taxonomies: no taxonomy whose code does not end in " 4.2"
    /// has <c>TableGroup</c> nodes, or <c>BusinessTable</c> rows with a real parent; and,
    /// symmetrically, no 4.2 taxonomy has orphan <c>BusinessTable</c> rows (Parent = 0).
    /// </summary>
    [DataFact]
    public void TheTreeOnlyExistsInThe42Taxonomies()
    {
        var taxonomyCodeById = ReadTaxonomyCodes();

        var taxonomyIdsWithGroupNodes = ReadIntColumn(
            "SELECT DISTINCT \"TaxonomyID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'TableGroup'");
        var nonCurrentWithGroups = taxonomyIdsWithGroupNodes
            .Where(id => !taxonomyCodeById.TryGetValue(id, out var code) || !code.EndsWith(" 4.2", StringComparison.Ordinal))
            .ToList();
        Assert.True(nonCurrentWithGroups.Count == 0, $"Non-4.2 taxonomies with TableGroup nodes: {string.Join(",", nonCurrentWithGroups)}");

        var taxonomyIdsWithRealParentTables = ReadIntColumn(
            "SELECT DISTINCT \"TaxonomyID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"ParentTemplateOrTableID\" <> 0");
        var nonCurrentWithRealParent = taxonomyIdsWithRealParentTables
            .Where(id => !taxonomyCodeById.TryGetValue(id, out var code) || !code.EndsWith(" 4.2", StringComparison.Ordinal))
            .ToList();
        Assert.True(nonCurrentWithRealParent.Count == 0, $"Non-4.2 taxonomies with BusinessTable rows with a real parent: {string.Join(",", nonCurrentWithRealParent)}");

        var taxonomyIdsWithOrphans = ReadIntColumn(
            "SELECT DISTINCT \"TaxonomyID\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"ParentTemplateOrTableID\" = 0");
        var currentWithOrphans = taxonomyIdsWithOrphans
            .Where(id => taxonomyCodeById.TryGetValue(id, out var code) && code.EndsWith(" 4.2", StringComparison.Ordinal))
            .ToList();
        Assert.True(currentWithOrphans.Count == 0, $"4.2 taxonomies with an orphan BusinessTable: {string.Join(",", currentWithOrphans)}");
    }

    // ------------------------------------------------------------------
    // 4 - mTable: measured columns
    // ------------------------------------------------------------------

    /// <summary>
    /// <c>XbrlFilingIndicatorCode</c> = the code of the table's TEMPLATE, WITHOUT the
    /// <c>eba_tg</c> prefix. It checks, in the 847 rows, that
    /// <c>'eba_tg' + XbrlFilingIndicatorCode</c> exists among the codes of the <c>Level</c> 2 nodes
    /// (the 563 distinct templates) -- the check is GLOBAL, not per taxonomy: the template is a
    /// per-table concept, not per (table, taxonomy) pair, and its tree nodes are only materialized
    /// where applicable.
    /// </summary>
    [DataFact]
    public void MTable_XbrlFilingIndicatorCode_IsTheTemplateCodeWithoutPrefix()
    {
        var level2Codes = ReadStringColumn(
                "SELECT DISTINCT \"TemplateOrTableCode\" FROM \"mTemplateOrTable\" WHERE \"Level\" = 2 AND \"TemplateOrTableType\" = 'TableGroup'")
            .Where(c => c is not null)
            .Select(c => c!)
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(563, level2Codes.Count);

        var indicatorRows = ReadPairsStringString(
            "SELECT \"TableCode\", \"XbrlFilingIndicatorCode\" FROM \"mTable\"");

        Assert.Equal(847, indicatorRows.Count);

        var missing = indicatorRows
            .Where(r => r.B is null || !level2Codes.Contains("eba_tg" + r.B))
            .ToList();

        Assert.True(
            missing.Count == 0,
            $"{missing.Count} mTable rows whose 'eba_tg' + XbrlFilingIndicatorCode does not exist among "
            + $"the Level 2 nodes. Examples: {string.Join(", ", missing.Take(10).Select(m => $"{m.A}->{m.B}"))}");
    }

    /// <summary><c>TableLabel</c> = <c>&lt;code&gt;:&lt;Name&gt;</c> -- the target prepends the code and a colon, in the 847 rows.</summary>
    [DataFact]
    public void MTable_TableLabel_StartsWithCodeColon_In847Rows()
    {
        var rows = ReadPairsStringString("SELECT \"TableCode\", \"TableLabel\" FROM \"mTable\"");
        Assert.Equal(847, rows.Count);

        var mismatches = rows.Where(r => r.B is null || !r.B.StartsWith(r.A + ":", StringComparison.Ordinal)).ToList();
        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} rows whose TableLabel does not start with '<code>:'. Examples: "
            + string.Join(", ", mismatches.Take(10).Select(m => $"{m.A}->{m.B}")));
    }

    /// <summary>
    /// The name is NOT trimmed: several labels keep a trailing space exactly as in the source, and
    /// that is correct -- <c>Trim</c> would fix some and break others. This test does not compare
    /// against the reference (no comparison is relaxed); it compares AGAINST THE SOURCE ITSELF, row
    /// by row, reading <c>TableVersion.Name</c> directly from the Access database with
    /// <see cref="Dpm20AccessReader"/>, for a batch of tables whose source name ends in a space --
    /// showing that the space survives without anyone trimming it.
    /// </summary>
    [DataFact]
    public void MTable_TableLabel_DoesNotTrimTheName_AgainstTheSourceRowByRow()
    {
        RepoPaths.EnsureAccessDpm20DatabaseExists();

        using var reader = new Dpm20AccessReader(RepoPaths.AccessDpm20DatabasePath);
        reader.Open();
        var tableVersionsWithTrailingSpaceName = reader.ReadTableVersions()
            .Where(tv => tv.Name is not null && tv.Name.EndsWith(' '))
            .ToList();

        Assert.True(
            tableVersionsWithTrailingSpaceName.Count > 0,
            "There is no current TableVersion whose Name ends in a space in the source; the witness "
            + "case (9 labels with a trailing space) cannot be checked this way.");

        // Note: mTable has 847 ROWS but 788 distinct CODES (a code can appear in more than one
        // table-taxonomy pair); the label is a function of the code, not of the pair, so grouping
        // and taking the first one is correct -- no information is lost in the comparison.
        var generatedLabelsByCode = ReadPairsStringString("SELECT \"TableCode\", \"TableLabel\" FROM \"mTable\"")
            .Where(r => r.B is not null)
            .GroupBy(r => r.A, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First().B!, StringComparer.Ordinal);

        var checkedCount = 0;
        var mismatches = new List<string>();
        foreach (var tv in tableVersionsWithTrailingSpaceName)
        {
            if (!generatedLabelsByCode.TryGetValue(tv.Code, out var generatedLabel))
            {
                continue; // e.g. abstract, or excluded because of DORA: it emits no mTable row.
            }

            checkedCount++;
            var expectedLabel = tv.Code + ":" + tv.Name;
            if (!string.Equals(generatedLabel, expectedLabel, StringComparison.Ordinal))
            {
                mismatches.Add($"{tv.Code}: expected '{expectedLabel}' (NOT trimmed), generated '{generatedLabel}'");
            }
        }

        Assert.True(checkedCount > 0, "None of the TableVersion rows with a Name ending in a space produces an mTable row; nothing to check.");
        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} of {checkedCount} labels with a trailing space in the source were NOT "
            + $"reproduced as they are (is it being trimmed?): {string.Join(" | ", mismatches.Take(10))}");
    }

    /// <summary><c>JsonBlob</c> = empty BLOB (not NULL, not a string) in all 847; <c>FromDate</c>, <c>ToDate</c>, <c>XbrlTableCode</c>, <c>YDimVal</c>, <c>ZDimVal</c> NULL.</summary>
    [DataFact]
    public void MTable_JsonBlobEmpty_And_DateAndDimensionFieldsNull()
    {
        Assert.Equal(847, CountRows("mTable"));

        Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM \"mTable\" WHERE \"JsonBlob\" IS NULL"));
        Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM \"mTable\" WHERE length(\"JsonBlob\") <> 0"));

        Assert.Equal(
            0,
            ScalarLong(
                "SELECT COUNT(*) FROM \"mTable\" WHERE \"FromDate\" IS NOT NULL OR \"ToDate\" IS NOT NULL "
                + "OR \"XbrlTableCode\" IS NOT NULL OR \"YDimVal\" IS NOT NULL OR \"ZDimVal\" IS NOT NULL"));
    }

    /// <summary><c>mTaxonomyTable.IsSimplyReuse</c> and <c>IsTableSource</c>: constant 1 in all 847.</summary>
    [DataFact]
    public void MTaxonomyTable_IsSimplyReuse_And_IsTableSource_AreConstant1_In847()
    {
        Assert.Equal(847, CountRows("mTaxonomyTable"));
        Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM \"mTaxonomyTable\" WHERE \"IsSimplyReuse\" <> 1"));
        Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM \"mTaxonomyTable\" WHERE \"IsTableSource\" <> 1"));
    }

    // ------------------------------------------------------------------
    // 5 - Against the reference, by CONTAINMENT, never by equality of counts.
    // ------------------------------------------------------------------

    /// <summary>
    /// The 788 <c>mTable</c> codes against <c>EBA_4.2_Hotfix.db</c>: PERFECT containment, 0 only in
    /// the reference. CRITICAL layer: coverage -- what is generated must contain the reference.
    /// </summary>
    [DataFact]
    public void MTable_TableCode_Contains_The788OfTheReference_PerfectContainment()
    {
        RepoPaths.EnsureReferenceDatabaseExists();

        var generatedCodes = ReadStringColumn("SELECT DISTINCT \"TableCode\" FROM \"mTable\"")
            .Where(c => c is not null).Select(c => c!).ToHashSet(StringComparer.Ordinal);
        Assert.Equal(788, generatedCodes.Count);

        using var referenceConnection = OpenReadOnly(RepoPaths.ReferenceDatabasePath);
        using var command = referenceConnection.CreateCommand();
        command.CommandText = "SELECT DISTINCT \"TableCode\" FROM \"mTable\"";
        var referenceCodes = new HashSet<string>(StringComparer.Ordinal);
        using (var readerCmd = command.ExecuteReader())
        {
            while (readerCmd.Read())
            {
                referenceCodes.Add(readerCmd.GetString(0));
            }
        }

        Assert.Equal(788, referenceCodes.Count);

        var onlyInReference = referenceCodes.Except(generatedCodes).ToList();
        Assert.True(
            onlyInReference.Count == 0,
            $"{onlyInReference.Count} mTable codes only in the reference (should be 0): "
            + string.Join(", ", onlyInReference.Take(20)));
    }

    // ------------------------------------------------------------------
    // 6 - Named cases
    // ------------------------------------------------------------------

    /// <summary>
    /// <c>S_04.00</c> appears as an orphan in <c>pay 4.1</c> (a taxonomy that the reference does not
    /// publish) and with a real parent in <c>pay 4.2</c>. Nominal test of the case, measured in the
    /// real .db: TaxonomyID of pay 4.1 -> ParentTemplateOrTableID = 0; TaxonomyID of pay 4.2 -> real
    /// parent.
    /// </summary>
    [DataFact]
    public void NamedCase_S0400_OrphanInPay41_WithARealParentInPay42()
    {
        var taxonomyCodeById = ReadTaxonomyCodes();

        var rows = ReadPairsIntWithCode(
            "SELECT tt.\"TaxonomyID\", bt.\"ParentTemplateOrTableID\" "
            + "FROM \"mTaxonomyTable\" tt "
            + "JOIN \"mTable\" mt ON mt.\"TableID\" = tt.\"TableID\" "
            + "JOIN \"mTemplateOrTable\" bt ON bt.\"TemplateOrTableID\" = tt.\"TableID\" AND bt.\"TemplateOrTableType\" = 'BusinessTable' "
            + "WHERE mt.\"TableCode\" = 'S_04.00'");

        Assert.Equal(2, rows.Count);

        var pay41 = rows.SingleOrDefault(r => taxonomyCodeById.GetValueOrDefault(r.A) == "pay 4.1");
        var pay42 = rows.SingleOrDefault(r => taxonomyCodeById.GetValueOrDefault(r.A) == "pay 4.2");

        Assert.True(pay41.A != 0, "The S_04.00 row in 'pay 4.1' was not found.");
        Assert.True(pay42.A != 0, "The S_04.00 row in 'pay 4.2' was not found.");

        Assert.Equal(0, pay41.B); // orphan
        Assert.NotEqual(0, pay42.B); // real parent
    }

    /// <summary>
    /// <c>C_34.02.b</c> DOES appear in <c>if 4.2</c>. It used to be a documented gap (the pair
    /// <c>(C_34.02.b, if 4.2)</c> was missing). The module composition declares <c>C_34.02.b</c> as
    /// an ABSTRACT table of <c>if 4.2</c>, and the abstract-closure rule adds its current concrete
    /// children when a composition references an abstract table -- closing exactly that gap. The
    /// discarded hypothesis (propagating the taxonomies of the whole GROUP, which overproduced 26
    /// pairs) remains discarded: the closure rule resolves the abstract table declared in the
    /// composition, not the group. It is stated as a PROPERTY by business key (never by ID) with a
    /// POSITIVE CONTROL: if <c>C_34.02.a</c> -- which was already present before -- stopped being
    /// found, the query would be wrongly written and the rest of the test would prove nothing.
    /// </summary>
    [DataFact]
    public void NamedCase_C3402b_AppearsInCorep42_AndInIf42()
    {
        var taxonomyCodeById = ReadTaxonomyCodes();

        List<string> TaxonomyCodesFor(string tableCode) => ReadIntColumn(
                "SELECT tt.\"TaxonomyID\" FROM \"mTaxonomyTable\" tt "
                + "JOIN \"mTable\" mt ON mt.\"TableID\" = tt.\"TableID\" WHERE mt.\"TableCode\" = '" + tableCode + "'")
            .Select(id => taxonomyCodeById.GetValueOrDefault(id) ?? "?")
            .ToList();

        // Positive control: C_34.02.a was already present BEFORE the abstract-closure rule -- if the
        // query does not find it, it is wrongly written and the result below about C_34.02.b proves
        // nothing.
        var codesForA = TaxonomyCodesFor("C_34.02.a");
        Assert.Contains("if 4.2", codesForA);
        Assert.Contains("corep 4.2", codesForA);

        var codesForB = TaxonomyCodesFor("C_34.02.b");
        Assert.Contains("corep 4.2", codesForB); // was already there, untouched by the rule
        Assert.Contains("if 4.2", codesForB); // the pair that the abstract-closure rule adds
    }

    /// <summary>
    /// The <c>Order</c> of the 48 orphans is a DECLARED CHOICE, not derived -- the reference uses
    /// another numbering (<c>esg 4.0</c> carries 632/633/634). This test is about INTERNAL
    /// COHERENCE (contiguous 0-based range within the Parent=0 group, which is what the code says
    /// it implements), never about equality with the reference -- comparing against the reference
    /// here would measure the internal counter of ITS generator, which must not be chased.
    /// </summary>
    [DataFact]
    public void OrderOfThe48Orphans_IsContiguous0To47_ByDeclaredChoice_NotAgainstTheReference()
    {
        var orders = ReadIntColumn(
                "SELECT \"Order\" FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"ParentTemplateOrTableID\" = 0")
            .OrderBy(o => o)
            .ToList();

        Assert.Equal(48, orders.Count);
        Assert.Equal(Enumerable.Range(0, 48), orders);
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private long CountRows(string table)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = $"SELECT COUNT(*) FROM \"{table}\"";
        return Convert.ToInt64(command.ExecuteScalar());
    }

    private long ScalarLong(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        return Convert.ToInt64(command.ExecuteScalar());
    }

    private string? ScalarString(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        var value = command.ExecuteScalar();
        return value is null or DBNull ? null : Convert.ToString(value);
    }

    private List<int> ReadIntColumn(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<int>();
        while (reader.Read())
        {
            values.Add(reader.GetInt32(0));
        }

        return values;
    }

    private List<string?> ReadStringColumn(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<string?>();
        while (reader.Read())
        {
            values.Add(reader.IsDBNull(0) ? null : reader.GetString(0));
        }

        return values;
    }

    private HashSet<(int A, int B)> ReadPairs(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new HashSet<(int, int)>();
        while (reader.Read())
        {
            values.Add((reader.GetInt32(0), reader.GetInt32(1)));
        }

        return values;
    }

    private List<(int A, int B, int C)> ReadIntTriples(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<(int, int, int)>();
        while (reader.Read())
        {
            values.Add((reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2)));
        }

        return values;
    }

    private List<(string A, int B, string C)> ReadTriples(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<(string, int, string)>();
        while (reader.Read())
        {
            values.Add((reader.GetValue(0)?.ToString() ?? string.Empty, reader.GetInt32(1), reader.GetValue(2)?.ToString() ?? string.Empty));
        }

        return values;
    }

    private List<(string A, string? B)> ReadPairsStringString(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<(string, string?)>();
        while (reader.Read())
        {
            values.Add((reader.GetString(0), reader.IsDBNull(1) ? null : reader.GetString(1)));
        }

        return values;
    }

    private List<(int A, int B)> ReadPairsIntWithCode(string sql)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<(int, int)>();
        while (reader.Read())
        {
            values.Add((reader.GetInt32(0), reader.GetInt32(1)));
        }

        return values;
    }

    private List<(string Code, int ParentId, int Order)> ReadCodeParentOrder(IReadOnlyCollection<string> codes)
    {
        var placeholders = string.Join(",", codes.Select((_, i) => $"$c{i}"));
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText =
            $"SELECT \"TemplateOrTableCode\", \"ParentTemplateOrTableID\", \"Order\" "
            + $"FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableCode\" IN ({placeholders})";

        var i = 0;
        foreach (var code in codes)
        {
            command.Parameters.AddWithValue($"$c{i}", code);
            i++;
        }

        using var reader = command.ExecuteReader();
        var values = new List<(string, int, int)>();
        while (reader.Read())
        {
            values.Add((reader.GetString(0), reader.GetInt32(1), reader.GetInt32(2)));
        }

        return values;
    }

    private Dictionary<int, string> ReadTaxonomyCodes()
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = "SELECT \"TaxonomyID\", \"TaxonomyCode\" FROM \"mTaxonomy\"";
        using var reader = command.ExecuteReader();

        var result = new Dictionary<int, string>();
        while (reader.Read())
        {
            result[reader.GetInt32(0)] = reader.GetString(1);
        }

        return result;
    }

    private static SqliteConnection OpenReadOnly(string path)
    {
        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = path,
            Mode = SqliteOpenMode.ReadOnly,
        }.ToString();

        var connection = new SqliteConnection(connectionString);
        connection.Open();
        return connection;
    }
}
