using EbaDpm.Converter.Tests.Schema;
using Microsoft.Data.Sqlite;

namespace EbaDpm.Converter.Tests.Dpm2;

/// <summary>
/// The first four tables of the DPM 2.0 dictionary - <c>mDomain</c>, <c>mDomainUnion</c>,
/// <c>mMember</c> and <c>mHierarchy</c> - verified over the real <c>.db</c> generated by the CLI
/// (<see cref="Dpm20SkeletonFixture"/>, collection <c>Dpm2Skeleton</c>): the same <c>--all</c>
/// conversion already loads these four tables (<c>Dpm20DictionaryLoader</c> is invoked
/// unconditionally in <c>CliRunner.RunConvertDpm20</c>), so the fixture is reused instead of
/// repeating a 755 MB read.
///
/// <c>mMetric</c> and <c>mDimension</c> are covered elsewhere: this class does NOT touch them.
///
/// The count figures come from the DPM 2.0 SOURCE, not from <c>EBA_4.2_Hotfix.db</c>. The
/// reference (150, 102, 13,130, 1,572) is NOT the target: comparing against it by census equality
/// would be wrongly framed. The comparisons against the reference that DO appear here are, without
/// exception, by BUSINESS KEY and by CONTAINMENT, never by total count.
/// </summary>
[Collection("Dpm2Skeleton")]
[Trait("Tier", "RealData")]
public sealed class Dpm20DictionaryLoaderTests(Dpm20SkeletonFixture fixture)
{
    // ------------------------------------------------------------------
    // Counts - figures of the SOURCE, measured, not of the reference.
    // ------------------------------------------------------------------

    [DataFact]
    public void MDomain_Has150Rows() => Assert.Equal(150, CountRows("mDomain"));

    [DataFact]
    public void MDomainUnion_Has102Rows_And41DistinctUnions()
    {
        Assert.Equal(102, CountRows("mDomainUnion"));
        Assert.Equal(41, ScalarLong("SELECT COUNT(DISTINCT UnionDomainID) FROM mDomainUnion"));
    }

    [DataFact]
    public void MMember_Has12949Rows() => Assert.Equal(12949, CountRows("mMember"));

    [DataFact]
    public void MHierarchy_Has1154Rows() => Assert.Equal(1154, CountRows("mHierarchy"));

    // ------------------------------------------------------------------
    // mDomain: 146 from Category + 4 synthesized
    // ------------------------------------------------------------------

    /// <summary><c>SE</c>, <c>_NA</c>, <c>_PR</c> and <c>_TE</c> do NOT produce a row in <c>mDomain</c>.</summary>
    [DataFact]
    public void MDomain_ExcludesSE_NA_PR_TE()
    {
        foreach (var code in new[] { "SE", "_NA", "_PR", "_TE" })
        {
            Assert.Equal(0, ScalarLong("SELECT COUNT(*) FROM mDomain WHERE DomainCode = $c", ("$c", code)));
        }
    }

    /// <summary>146 "normal" domains (from <c>Category</c>) + 4 synthesized = 150.</summary>
    [DataFact]
    public void MDomain_Has146FromCategory_Plus4Synthesized()
    {
        var synthesizedOrSentinel = new[] { "MET", "INT_NA", "STR_NA", string.Empty };
        var placeholders = string.Join(", ", synthesizedOrSentinel.Select((_, i) => $"$s{i}"));
        var parameters = synthesizedOrSentinel.Select((v, i) => ($"$s{i}", (object)v)).ToArray();

        var fromCategory = ScalarLong(
            $"SELECT COUNT(*) FROM mDomain WHERE DomainCode NOT IN ({placeholders})",
            parameters);

        Assert.Equal(146, fromCategory);
    }

    /// <summary>
    /// The 4 synthesized ones, column by column: <c>MET</c> (label "Metric domain",
    /// <c>DomainXBRLCode</c> = "MET" WITHOUT the <c>eba_*</c> prefix), <c>INT_NA</c>/<c>STR_NA</c>
    /// (typed, <c>Integer</c>/<c>NotEmptyString</c>) and the sentinel (<c>DomainCode</c> = empty
    /// string, label "Open").
    /// </summary>
    [DataFact]
    public void MDomain_TheFourSynthesizedDomains_MatchColumnByColumn()
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText =
            "SELECT DomainCode, DomainLabel, DomainXBRLCode, DataType, IsTypedDomain FROM mDomain WHERE DomainCode = $c";

        AssertDomainRow(command, "MET", "Metric domain", "MET", dataType: null, isTypedDomain: false);
        AssertDomainRow(
            command,
            "INT_NA",
            // The typo "dimensons" is copied VERBATIM from the source: it is NOT "corrected".
            "fictive domain created for string type properties used as typed dimensons",
            "eba_typ:INT_NA",
            dataType: "Integer",
            isTypedDomain: true);
        AssertDomainRow(
            command,
            "STR_NA",
            "fictive domain created for string type properties used as typed dimensons",
            "eba_typ:STR_NA",
            dataType: "NotEmptyString",
            isTypedDomain: true);

        using var sentinelCommand = fixture.GeneratedConnection.CreateCommand();
        sentinelCommand.CommandText = "SELECT DomainCode, DomainLabel FROM mDomain WHERE DomainLabel = 'Open'";
        using var reader = sentinelCommand.ExecuteReader();
        Assert.True(reader.Read(), "The sentinel was not found (DomainLabel = 'Open').");
        Assert.Equal(string.Empty, reader.GetString(0));
    }

    private static void AssertDomainRow(
        SqliteCommand command, string code, string label, string xbrlCode, string? dataType, bool isTypedDomain)
    {
        command.Parameters.Clear();
        command.Parameters.AddWithValue("$c", code);
        using var reader = command.ExecuteReader();
        Assert.True(reader.Read(), $"There is no row in mDomain with DomainCode='{code}'.");

        Assert.Equal(label, reader.GetString(1));
        Assert.Equal(xbrlCode, reader.GetString(2));

        if (dataType is null)
        {
            Assert.True(reader.IsDBNull(3), $"DataType of '{code}' should be NULL.");
        }
        else
        {
            Assert.Equal(dataType, reader.GetString(3));
        }

        Assert.Equal(isTypedDomain, reader.GetInt64(4) != 0);
    }

    /// <summary><c>IsTypedDomain</c> if and only if <c>NOT Category.IsEnumerated</c> - the 17 typed ones.</summary>
    [DataFact]
    public void MDomain_IsTypedDomain_Has17Rows()
        => Assert.Equal(17, ScalarLong("SELECT COUNT(*) FROM mDomain WHERE IsTypedDomain = 1"));

    /// <summary>
    /// <c>DomainXBRLCode</c> = <c>eba_typ:&lt;code&gt;</c> if typed, <c>eba_exp:&lt;code&gt;</c>
    /// otherwise - for the 146 domains from <c>Category</c> (the 4 synthesized ones have their own
    /// shape, already covered above).
    /// </summary>
    [DataFact]
    public void MDomain_DomainXBRLCode_FollowsTheTypedExplicitRule_ForTheCategoryDerivedRows()
    {
        var mismatches = ScalarLong(
            """
            SELECT COUNT(*) FROM mDomain
            WHERE DomainCode NOT IN ('MET', 'INT_NA', 'STR_NA', '')
              AND DomainXBRLCode != (CASE WHEN IsTypedDomain = 1 THEN 'eba_typ:' ELSE 'eba_exp:' END || DomainCode)
            """);

        Assert.Equal(0, mismatches);
    }

    /// <summary><c>DomainDescription</c> = empty string and <c>IsNillable</c> = 0 in all 150.</summary>
    [DataFact]
    public void MDomain_DomainDescription_IsEmptyString_AndIsNillable_IsZero_InAll150Rows()
    {
        Assert.Equal(150, ScalarLong("SELECT COUNT(*) FROM mDomain WHERE DomainDescription = ''"));
        Assert.Equal(150, ScalarLong("SELECT COUNT(*) FROM mDomain WHERE IsNillable = 0"));
    }

    // ------------------------------------------------------------------
    // mMember
    // ------------------------------------------------------------------

    /// <summary>
    /// <c>MemberXBRLCode</c> = <c>eba_&lt;DomainCode&gt;:&lt;MemberCode&gt;</c> outside <c>MET</c>,
    /// and <c>eba_met:&lt;code&gt;</c> for <c>MET</c>. No code carries a release suffix.
    /// </summary>
    [DataFact]
    public void MMember_MemberXBRLCode_FollowsTheDomainPrefixRule()
    {
        var outsideMetMismatches = ScalarLong(
            """
            SELECT COUNT(*) FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID
            WHERE d.DomainCode NOT IN ('MET', '')
              AND m.MemberXBRLCode != ('eba_' || d.DomainCode || ':' || m.MemberCode)
            """);
        Assert.Equal(0, outsideMetMismatches);

        // The "10,722 of 10,722" figure from an earlier investigation is NOT pinned here: measured
        // over the real .db there are 10,841 rows outside MET/sentinel (= 12,949 - 2,107 of MET - 1
        // sentinel), a count that was not rechecked after later adjustments to the MET domain. What
        // matters for the CRITICAL layer is the FORMAT (0 mismatches, checked above), not that
        // specific count; the arithmetic identity is left as documentation of the real measured
        // figure.
        var outsideMetTotal = ScalarLong(
            "SELECT COUNT(*) FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID WHERE d.DomainCode NOT IN ('MET', '')");
        Assert.Equal(CountRows("mMember") - 2107 - 1, outsideMetTotal);

        var metMismatches = ScalarLong(
            """
            SELECT COUNT(*) FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID
            WHERE d.DomainCode = 'MET' AND m.MemberXBRLCode != ('eba_met:' || m.MemberCode)
            """);
        Assert.Equal(0, metMismatches);

        // The two comparisons above are exact string EQUALITY: by construction they leave no room
        // for a release suffix slipping into MemberXBRLCode.
    }

    /// <summary>Zero duplicates by (<c>DomainID</c>, <c>MemberCode</c>) in the 12,949 rows.</summary>
    [DataFact]
    public void MMember_HasNoDuplicates_ByDomainAndMemberCode()
    {
        var duplicateGroups = ScalarLong(
            "SELECT COUNT(*) FROM (SELECT DomainID, MemberCode FROM mMember GROUP BY DomainID, MemberCode HAVING COUNT(*) > 1)");
        Assert.Equal(0, duplicateGroups);
    }

    /// <summary>
    /// Exception E-7: the 109 members of the <c>qIO</c> domain ARE EMITTED - <c>eba_qIO:qx0</c>
    /// (the "Not applicable", <c>IsDefaultMember</c> = 1) and <c>eba_qIO:qx2000</c> ...
    /// <c>eba_qIO:qx2107</c>, NOT contiguous. The 4.2 reference lacks them: it is the documented
    /// reference defect that we do NOT reproduce, and this test exists so that nobody deletes them
    /// believing they "match better" with the reference - the comparison of members against the
    /// reference is ALWAYS by containment, never by census equality.
    /// </summary>
    [DataFact]
    public void MMember_EmitsThe109QIOMembers_DespiteTheReferenceHavingZero_E7()
    {
        var qioMembers = ReadStringColumn(
            """
            SELECT m.MemberCode FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID
            WHERE d.DomainCode = 'qIO'
            ORDER BY m.MemberCode
            """);

        Assert.Equal(109, qioMembers.Count);
        Assert.Contains("qx0", qioMembers);
        Assert.Contains("qx2000", qioMembers);
        Assert.Contains("qx2107", qioMembers);

        // "Not contiguous": the statement describes the COMPLETE set (qx0 + qx2000...qx2107), not a
        // gap inside the qx2xxx block - measured: the 108 qx2xxx codes DO form a contiguous block
        // (2000..2107, no gaps), but qx0 is 1,999 numbers away from qx2000, so the set of 109 is NOT
        // a single contiguous numeric sequence.
        var numericSuffixes = qioMembers
            .Select(c => int.Parse(c["qx".Length..]))
            .OrderBy(n => n)
            .ToList();
        Assert.Equal(109, numericSuffixes.Count);

        var largestGap = numericSuffixes.Zip(numericSuffixes.Skip(1), (a, b) => b - a).Max();
        Assert.True(largestGap > 1, $"A gap was expected (qx0 vs qx2000...), and the largest measured jump is {largestGap}.");

        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText =
            """
            SELECT m.IsDefaultMember FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID
            WHERE d.DomainCode = 'qIO' AND m.MemberCode = 'qx0'
            """;
        var isDefault = Convert.ToInt64(command.ExecuteScalar());
        Assert.Equal(1, isDefault);
    }

    /// <summary>
    /// The members of the <c>MET</c> domain are 2,107, and against the 2,104 codes of the reference
    /// EXACTLY three are in excess: <c>old-FGT</c>, <c>old-ei912</c> and <c>old-pi418</c>. Not one
    /// more, and none is missing - checked by name, not by count.
    /// </summary>
    [DataFact]
    public void MMember_MetDomain_ExceedsReferenceByExactlyTheThreeOldCodes()
    {
        RepoPaths.EnsureReferenceDatabaseExists();

        var generatedMetCodes = ReadStringColumn(
            "SELECT m.MemberCode FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID WHERE d.DomainCode = 'MET'")
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(2107, generatedMetCodes.Count);

        using var referenceConnection = OpenReadOnly(RepoPaths.ReferenceDatabasePath);
        var referenceMetCodes = ReadStringColumn(
            referenceConnection,
            "SELECT m.MemberCode FROM mMember m JOIN mDomain d ON m.DomainID = d.DomainID WHERE d.DomainCode = 'MET'")
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(2104, referenceMetCodes.Count);

        var onlyInReference = referenceMetCodes.Except(generatedMetCodes).ToList();
        Assert.Empty(onlyInReference);

        var onlyInGenerated = generatedMetCodes.Except(referenceMetCodes).OrderBy(c => c, StringComparer.Ordinal).ToList();
        Assert.Equal(["old-FGT", "old-ei912", "old-pi418"], onlyInGenerated);
    }

    // ------------------------------------------------------------------
    // mHierarchy
    // ------------------------------------------------------------------

    /// <summary>1,154 = <c>SubCategory</c>, 1 to 1. It is not split by <c>SubCategoryVersion</c>.</summary>
    [DataFact]
    public void MHierarchy_MapsOneToOne_WithSourceSubCategory()
    {
        RepoPaths.EnsureAccessDpm20DatabaseExists();

        using var reader = new EbaDpm.Converter.Core.Access.Dpm20.Dpm20AccessReader(RepoPaths.AccessDpm20DatabasePath);
        reader.Open();
        var subCategoryCount = reader.ReadSubCategories().Count();

        Assert.Equal(1154, subCategoryCount);
        Assert.Equal(subCategoryCount, CountRows("mHierarchy"));
    }

    /// <summary>
    /// The 16 subcategories hanging from <c>_PR</c> go to the <c>MET</c> domain: they are exactly 16
    /// of the 21 <c>MET</c> hierarchies of the reference, with perfect containment (0 only in the
    /// source). The remaining 5 are <c>AT6</c>, <c>AT9</c>, <c>AT11</c>, <c>AT81</c> and
    /// <c>AT106</c> - named one by one, the DD-16 exception applied by business key, never as a
    /// general rule.
    /// </summary>
    [DataFact]
    public void MHierarchy_MetDomain_Contains16Of21ReferenceHierarchies_TheFiveMissingAreDD16()
    {
        RepoPaths.EnsureReferenceDatabaseExists();

        var generatedMetHierarchies = ReadStringColumn(
            "SELECT h.HierarchyCode FROM mHierarchy h JOIN mDomain d ON h.DomainID = d.DomainID WHERE d.DomainCode = 'MET'")
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(16, generatedMetHierarchies.Count);

        using var referenceConnection = OpenReadOnly(RepoPaths.ReferenceDatabasePath);
        var referenceMetHierarchies = ReadStringColumn(
            referenceConnection,
            "SELECT h.HierarchyCode FROM mHierarchy h JOIN mDomain d ON h.DomainID = d.DomainID WHERE d.DomainCode = 'MET'")
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(21, referenceMetHierarchies.Count);

        // Perfect containment: 0 only in the source.
        var onlyInGenerated = generatedMetHierarchies.Except(referenceMetHierarchies).ToList();
        Assert.Empty(onlyInGenerated);

        // The remaining 5, named - the DD-16 exception, applied by business key.
        var missingFromGenerated = referenceMetHierarchies.Except(generatedMetHierarchies)
            .OrderBy(c => c, StringComparer.Ordinal)
            .ToList();
        Assert.Equal(["AT106", "AT11", "AT6", "AT81", "AT9"], missingFromGenerated);
    }

    /// <summary>
    /// A hierarchy <c>('IM','test')</c> with the label "testing" exists. It is emitted: it is
    /// already-known debris of the source, it is not filtered out.
    /// </summary>
    [DataFact]
    public void MHierarchy_EmitsTheImTestHierarchy_KnownSourceDebris()
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText =
            """
            SELECT h.HierarchyLabel FROM mHierarchy h JOIN mDomain d ON h.DomainID = d.DomainID
            WHERE d.DomainCode = 'IM' AND h.HierarchyCode = 'test'
            """;
        var label = command.ExecuteScalar();

        Assert.NotNull(label);
        Assert.Equal("testing", Assert.IsType<string>(label));
    }

    // ------------------------------------------------------------------
    // mDomainUnion: the invariant - a union is NEVER materialized
    // ------------------------------------------------------------------

    /// <summary>
    /// The union is NOT materialized: in NONE of the 41 unions are the members of the union domain
    /// the sum of those of its components. Internal invariant, without looking at any reference -
    /// it is the one that would detect someone "fixing" <c>mDomainUnion</c> by expanding members.
    /// </summary>
    [DataFact]
    public void MDomainUnion_NeverMaterializesMembers_ForAnyOfThe41Unions()
    {
        using var unionsCommand = fixture.GeneratedConnection.CreateCommand();
        unionsCommand.CommandText = "SELECT DISTINCT UnionDomainID FROM mDomainUnion";
        var unionDomainIds = new List<long>();
        using (var reader = unionsCommand.ExecuteReader())
        {
            while (reader.Read())
            {
                unionDomainIds.Add(reader.GetInt64(0));
            }
        }

        Assert.Equal(41, unionDomainIds.Count);

        var offendingUnions = new List<string>();

        foreach (var unionDomainId in unionDomainIds)
        {
            var ownMemberCount = ScalarLong(
                "SELECT COUNT(*) FROM mMember WHERE DomainID = $id", ("$id", unionDomainId));

            using var componentsCommand = fixture.GeneratedConnection.CreateCommand();
            componentsCommand.CommandText = "SELECT UnitedDomainID FROM mDomainUnion WHERE UnionDomainID = $id";
            componentsCommand.Parameters.AddWithValue("$id", unionDomainId);

            var componentDomainIds = new List<long>();
            using (var reader = componentsCommand.ExecuteReader())
            {
                while (reader.Read())
                {
                    componentDomainIds.Add(reader.GetInt64(0));
                }
            }

            var sumOfComponentMembers = componentDomainIds.Sum(
                componentId => ScalarLong("SELECT COUNT(*) FROM mMember WHERE DomainID = $id", ("$id", componentId)));

            if (ownMemberCount == sumOfComponentMembers)
            {
                offendingUnions.Add(
                    $"UnionDomainID={unionDomainId}: {ownMemberCount} own members == {sumOfComponentMembers} sum of components");
            }
        }

        Assert.True(
            offendingUnions.Count == 0,
            "mDomainUnion appears to be materialized in: " + string.Join(" | ", offendingUnions));
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private long CountRows(string table)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = $"SELECT COUNT(*) FROM \"{table}\"";
        return Convert.ToInt64(command.ExecuteScalar());
    }

    private long ScalarLong(string sql, params (string Name, object Value)[] parameters)
    {
        using var command = fixture.GeneratedConnection.CreateCommand();
        command.CommandText = sql;
        foreach (var (name, value) in parameters)
        {
            command.Parameters.AddWithValue(name, value);
        }

        return Convert.ToInt64(command.ExecuteScalar());
    }

    private List<string> ReadStringColumn(string sql) => ReadStringColumn(fixture.GeneratedConnection, sql);

    private static List<string> ReadStringColumn(SqliteConnection connection, string sql)
    {
        using var command = connection.CreateCommand();
        command.CommandText = sql;
        using var reader = command.ExecuteReader();

        var values = new List<string>();
        while (reader.Read())
        {
            if (!reader.IsDBNull(0))
            {
                values.Add(reader.GetString(0));
            }
        }

        return values;
    }

    private static SqliteConnection OpenReadOnly(string path)
    {
        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = path,
            Mode = SqliteOpenMode.ReadOnly,
        }.ToString();

        var connection = new SqliteConnection(connectionString);
        connection.Open();
        return connection;
    }
}
