using Microsoft.Data.Sqlite;

namespace EbaDpm.Converter.Tests.Schema;

/// <summary>
/// "Schema" test level: the database generated by
/// <see cref="EbaDpm.Converter.Core.Sqlite.SchemaCreator"/> must be structurally identical to the
/// reference contract <c>EBA_4.2_Hotfix.db</c>. The comparison is as strict as possible: not one
/// table, column, type, PK, FK or index more or less.
///
/// The schema is generated (<see cref="SchemaFixture"/>) only once per class; all the tests only
/// read (PRAGMAs and SELECT), so they are independent of each other and can run in any order.
/// </summary>
public sealed class SchemaComparisonTests : IClassFixture<SchemaFixture>
{
    private const string DataMissingSentinel = "__DATA_DIRECTORY_MISSING__";

    private readonly SchemaFixture _fixture;

    public SchemaComparisonTests(SchemaFixture fixture)
    {
        _fixture = fixture;
    }

    // ------------------------------------------------------------------
    // 1. Table set
    // ------------------------------------------------------------------

    [DataFact]
    public void GeneratedDatabase_HasIdenticalTableSet_ToReference()
    {
        var referenceTables = SchemaInspector.GetTableNames(_fixture.ReferenceConnection).ToHashSet(StringComparer.Ordinal);
        var generatedTables = SchemaInspector.GetTableNames(_fixture.GeneratedConnection).ToHashSet(StringComparer.Ordinal);

        var missing = referenceTables.Except(generatedTables).OrderBy(n => n, StringComparer.Ordinal).ToList();
        var extra = generatedTables.Except(referenceTables).OrderBy(n => n, StringComparer.Ordinal).ToList();

        var message =
            "The table set of the generated database does not match the contract " +
            $"({RepoPaths.ReferenceDatabaseFileName}).\n" +
            $"Contract tables: {referenceTables.Count}. Generated tables: {generatedTables.Count}.\n" +
            $"Missing from the generated one ({missing.Count}): {(missing.Count == 0 ? "(none)" : string.Join(", ", missing))}\n" +
            $"Extra in the generated one ({extra.Count}): {(extra.Count == 0 ? "(none)" : string.Join(", ", extra))}";

        Assert.True(missing.Count == 0 && extra.Count == 0, message);
    }

    // ------------------------------------------------------------------
    // 2. Columns per table: name, type, order, NOT NULL, PK membership
    // ------------------------------------------------------------------

    public static IEnumerable<object[]> ReferenceTableNames()
    {
        if (!TryGetReferenceTableNamesForDiscovery(out var names, out _))
        {
            yield return new object[] { DataMissingSentinel };
            yield break;
        }

        foreach (var name in names)
        {
            yield return new object[] { name };
        }
    }

    [DataTheory]
    [MemberData(nameof(ReferenceTableNames))]
    public void GeneratedTable_HasIdenticalColumns_ToReference(string tableName)
    {
        FailIfDataMissingSentinel(tableName);

        var referenceColumns = SchemaInspector.GetColumns(_fixture.ReferenceConnection, tableName);
        var generatedColumns = SchemaInspector.GetColumns(_fixture.GeneratedConnection, tableName);

        var differences = new List<string>();

        var maxCount = Math.Max(referenceColumns.Count, generatedColumns.Count);
        for (var i = 0; i < maxCount; i++)
        {
            var reference = i < referenceColumns.Count ? referenceColumns[i] : null;
            var generated = i < generatedColumns.Count ? generatedColumns[i] : null;

            if (reference is null)
            {
                differences.Add($"  position {i}: extra in the generated one -> {generated}");
                continue;
            }

            if (generated is null)
            {
                differences.Add($"  position {i}: missing from the generated one -> expected {reference}");
                continue;
            }

            if (reference.Name != generated.Name)
            {
                differences.Add($"  position {i}: different name -> expected '{reference.Name}', actual '{generated.Name}'");
            }

            if (!string.Equals(reference.DeclaredType, generated.DeclaredType, StringComparison.Ordinal))
            {
                differences.Add(
                    $"  column '{reference.Name}': different type -> expected '{reference.DeclaredType}', " +
                    $"actual '{generated.DeclaredType}'");
            }

            if (reference.NotNull != generated.NotNull)
            {
                differences.Add(
                    $"  column '{reference.Name}': different NOT NULL -> expected {reference.NotNull}, " +
                    $"actual {generated.NotNull}");
            }

            if (reference.PrimaryKeyPosition != generated.PrimaryKeyPosition)
            {
                differences.Add(
                    $"  column '{reference.Name}': different PK position -> expected {reference.PrimaryKeyPosition}, " +
                    $"actual {generated.PrimaryKeyPosition}");
            }
        }

        var message =
            $"Table '{tableName}': the columns of the generated database differ from the contract.\n" +
            $"Expected (reference, {referenceColumns.Count} columns): {string.Join(" | ", referenceColumns)}\n" +
            $"Actual (generated, {generatedColumns.Count} columns): {string.Join(" | ", generatedColumns)}\n" +
            string.Join("\n", differences);

        Assert.True(differences.Count == 0, message);
    }

    // ------------------------------------------------------------------
    // 3. Foreign keys per table
    // ------------------------------------------------------------------

    [DataTheory]
    [MemberData(nameof(ReferenceTableNames))]
    public void GeneratedTable_HasIdenticalForeignKeys_ToReference(string tableName)
    {
        FailIfDataMissingSentinel(tableName);

        // PRAGMA foreign_key_list does not guarantee a stable order: sort before comparing.
        var referenceForeignKeys = SchemaInspector.GetForeignKeys(_fixture.ReferenceConnection, tableName)
            .OrderBy(fk => fk.FromColumn, StringComparer.Ordinal)
            .ThenBy(fk => fk.ToTable, StringComparer.Ordinal)
            .ThenBy(fk => fk.ToColumn, StringComparer.Ordinal)
            .ToList();

        var generatedForeignKeys = SchemaInspector.GetForeignKeys(_fixture.GeneratedConnection, tableName)
            .OrderBy(fk => fk.FromColumn, StringComparer.Ordinal)
            .ThenBy(fk => fk.ToTable, StringComparer.Ordinal)
            .ThenBy(fk => fk.ToColumn, StringComparer.Ordinal)
            .ToList();

        var missing = referenceForeignKeys.Except(generatedForeignKeys).ToList();
        var extra = generatedForeignKeys.Except(referenceForeignKeys).ToList();

        var message =
            $"Table '{tableName}': the foreign keys of the generated database differ from the contract.\n" +
            $"Expected (reference, {referenceForeignKeys.Count} FKs): {string.Join(" | ", referenceForeignKeys)}\n" +
            $"Actual (generated, {generatedForeignKeys.Count} FKs): {string.Join(" | ", generatedForeignKeys)}\n" +
            $"Missing from the generated one: {(missing.Count == 0 ? "(none)" : string.Join(" | ", missing))}\n" +
            $"Extra in the generated one: {(extra.Count == 0 ? "(none)" : string.Join(" | ", extra))}";

        Assert.True(missing.Count == 0 && extra.Count == 0, message);
    }

    // ------------------------------------------------------------------
    // 4. Explicit indexes (not the PK/UNIQUE autoindexes)
    // ------------------------------------------------------------------

    [DataFact]
    public void GeneratedDatabase_HasIdenticalExplicitIndexes_ToReference()
    {
        var referenceIndexes = SchemaInspector.GetExplicitIndexes(_fixture.ReferenceConnection)
            .OrderBy(i => i.TableName, StringComparer.Ordinal).ThenBy(i => i.IndexName, StringComparer.Ordinal)
            .ToList();
        var generatedIndexes = SchemaInspector.GetExplicitIndexes(_fixture.GeneratedConnection)
            .OrderBy(i => i.TableName, StringComparer.Ordinal).ThenBy(i => i.IndexName, StringComparer.Ordinal)
            .ToList();

        var referenceSignatures = referenceIndexes
            .Select(i => (i.TableName, i.IsUnique, Columns: string.Join(",", i.Columns)))
            .OrderBy(s => s.TableName, StringComparer.Ordinal).ThenBy(s => s.Columns, StringComparer.Ordinal)
            .ToList();
        var generatedSignatures = generatedIndexes
            .Select(i => (i.TableName, i.IsUnique, Columns: string.Join(",", i.Columns)))
            .OrderBy(s => s.TableName, StringComparer.Ordinal).ThenBy(s => s.Columns, StringComparer.Ordinal)
            .ToList();

        var missing = referenceSignatures.Except(generatedSignatures).ToList();
        var extra = generatedSignatures.Except(referenceSignatures).ToList();

        var message =
            "The explicit (non-autoindex) indexes of the generated database differ from the contract. " +
            $"Compared by (table, columns, uniqueness) because the index name is not a stable " +
            "business key.\n" +
            $"Reference ({referenceIndexes.Count}): {string.Join(" | ", referenceIndexes)}\n" +
            $"Generated ({generatedIndexes.Count}): {string.Join(" | ", generatedIndexes)}\n" +
            $"Missing from the generated one: {(missing.Count == 0 ? "(none)" : string.Join(" | ", missing))}\n" +
            $"Extra in the generated one: {(extra.Count == 0 ? "(none)" : string.Join(" | ", extra))}";

        Assert.True(missing.Count == 0 && extra.Count == 0, message);
    }

    // ------------------------------------------------------------------
    // 5. The generated database holds no data
    // ------------------------------------------------------------------

    [DataTheory]
    [MemberData(nameof(ReferenceTableNames))]
    public void GeneratedTable_HasZeroRows(string tableName)
    {
        FailIfDataMissingSentinel(tableName);

        // Only compare against tables that really exist in the generated database: if the table
        // does not exist, GeneratedDatabase_HasIdenticalTableSet_ToReference already reports it
        // with its own evidence; this test must not mask that failure with a different SQL error.
        var generatedTables = SchemaInspector.GetTableNames(_fixture.GeneratedConnection).ToHashSet(StringComparer.Ordinal);
        if (!generatedTables.Contains(tableName))
        {
            return;
        }

        var rowCount = SchemaInspector.GetRowCount(_fixture.GeneratedConnection, tableName);

        Assert.True(
            rowCount == 0,
            $"Table '{tableName}': expected 0 rows in the database just created by " +
            $"SchemaCreator.Create, but it contains {rowCount}.");
    }

    // ------------------------------------------------------------------
    // Discovery infrastructure / sentinel for a missing data directory
    // ------------------------------------------------------------------

    private static bool TryGetReferenceTableNamesForDiscovery(out List<string> names, out string? error)
    {
        try
        {
            RepoPaths.EnsureReferenceDatabaseExists();

            var connectionString = new SqliteConnectionStringBuilder
            {
                DataSource = RepoPaths.ReferenceDatabasePath,
                Mode = SqliteOpenMode.ReadOnly,
            }.ToString();

            using var connection = new SqliteConnection(connectionString);
            connection.Open();
            names = SchemaInspector.GetTableNames(connection);
            error = null;
            return true;
        }
        catch (Exception ex)
        {
            names = new List<string>();
            error = ex.Message;
            return false;
        }
    }

    private static void FailIfDataMissingSentinel(string tableName)
    {
        if (tableName != DataMissingSentinel)
        {
            return;
        }

        TryGetReferenceTableNamesForDiscovery(out _, out var error);
        Assert.Fail(
            "Could not enumerate the tables of the reference database " +
            $"'{RepoPaths.ReferenceDatabaseFileName}' to generate the cases of this test. " +
            $"Detail: {error}");
    }
}
