using System.Globalization;
using EbaDpm.Converter.Core.Mapping;
using Microsoft.Data.Sqlite;

namespace EbaDpm.Converter.Tests.Dictionary;

/// <summary>
/// "Integrity" level over the dictionary generated by <c>SkeletonLoader</c> +
/// <c>DictionaryLoader</c>: counts, FKs without orphans and coherence of the hierarchy trees.
/// Critical layer: these tests fail the build.
///
/// Reference run: <c>--taxonomies "COREP 3.2"</c> over
/// <c>Data/DPM 1.0 Database_v4_1_20250709.accdb</c> (<see cref="DictionaryFixture"/>).
///
/// The dictionary is loaded WITHOUT a taxonomy filter (see the header comment of
/// <c>DictionaryLoader</c>): <c>mDomain</c>, <c>mMember</c>, <c>mDimension</c>, <c>mMetric</c>,
/// <c>mHierarchy</c> and <c>mHierarchyNode</c> must therefore contain ALL the rows of the
/// Access database, regardless of the selected taxonomy. The counts in this file verify it
/// explicitly against the Access itself.
/// </summary>
[Collection("Dictionary")]
public sealed class IntegrityTests
{
    private readonly DictionaryFixture _fixture;

    public IntegrityTests(DictionaryFixture fixture)
    {
        _fixture = fixture;
    }

    // ------------------------------------------------------------------
    // 1. Counts per table
    // ------------------------------------------------------------------

    [DataTheory]
    // mDomain: +1 for the "Open" 9999 sentinel domain, with no source in the Access.
    [InlineData("mDomain", "Domain", 1)]
    // mMember: -1 for member 999 (x999), which is consumed without being emitted, +1 for the
    // "Open" 9999 sentinel: the net is 0, although the set of IDs changes.
    [InlineData("mMember", "Member", 0)]
    // mDimension: EXACTLY 864 = 864 (MET is not synthesised, the Access ATY dimension is
    // RENAMED -same row, same DimensionID- so it adds nothing to the census).
    [InlineData("mDimension", "Dimension", 0)]
    [InlineData("mMetric", "Metric", 0)]
    [InlineData("mHierarchy", "Hierarchy", 0)]
    [InlineData("mHierarchyNode", "HierarchyNode", 0)]
    public void RowCount_MatchesAccessSourceExactly_WithoutTaxonomyFilter(string sqliteTable, string accessTable, int syntheticRowsExpected)
    {
        var generatedCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, $"SELECT COUNT(*) FROM \"{sqliteTable}\"");

        var accessCount = _fixture.AccessReader
            .Query($"SELECT COUNT(*) FROM [{accessTable}]")
            .Select(r => Convert.ToInt64(r.GetValue(0)))
            .Single();

        Assert.True(
            generatedCount == accessCount + syntheticRowsExpected,
            $"{sqliteTable} has {generatedCount} generated rows versus {accessCount} in " +
            $"Access.{accessTable} (+{syntheticRowsExpected} synthetic rows expected). The dictionary is not " +
            "filtered by taxonomy: any unexplained difference is a data loss or a duplication.");
    }

    [DataFact]
    public void RowCounts_Informative_ConceptAndConceptTranslation()
    {
        // mConcept and mConceptTranslation DO depend on which concepts are reachable from what is
        // emitted (there is no exact source count to compare them 1:1 with): they are reported as
        // evidence, not asserted against a fixed figure.
        var conceptCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, "SELECT COUNT(*) FROM \"mConcept\"");
        var translationCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, "SELECT COUNT(*) FROM \"mConceptTranslation\"");

        Assert.True(conceptCount > 0, "mConcept is empty; concepts reachable from the dictionary were expected.");
        Assert.True(translationCount > 0, "mConceptTranslation is empty; it is synthesised from the *Label/*Description columns.");
    }

    // ------------------------------------------------------------------
    // 2. FKs without orphans (ConceptID -> mConcept, DomainID -> mDomain,
    //    MemberID/DefaultMemberID -> mMember, and the rest of the dictionary)
    // ------------------------------------------------------------------

    [DataTheory]
    // ConceptID -> mConcept, in the dictionary tables
    [InlineData("mDomain", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mMember", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mDimension", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mHierarchy", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mHierarchyNode", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mConceptTranslation", "ConceptID", "mConcept", "ConceptID")]
    // DomainID -> mDomain
    [InlineData("mMember", "DomainID", "mDomain", "DomainID")]
    [InlineData("mDimension", "DomainID", "mDomain", "DomainID")]
    [InlineData("mHierarchy", "DomainID", "mDomain", "DomainID")]
    // MemberID/DefaultMemberID -> mMember
    [InlineData("mDimension", "DefaultMemberID", "mMember", "MemberID")]
    [InlineData("mHierarchyNode", "MemberID", "mMember", "MemberID")]
    [InlineData("mHierarchyNode", "ParentMemberID", "mMember", "MemberID")]
    [InlineData("mMetric", "CorrespondingMemberID", "mMember", "MemberID")]
    // HierarchyID -> mHierarchy (tree support)
    [InlineData("mHierarchyNode", "HierarchyID", "mHierarchy", "HierarchyID")]
    // mConcept -> mOwner / mRelease
    [InlineData("mConcept", "OwnerID", "mOwner", "OwnerID")]
    [InlineData("mConcept", "ReleaseID", "mRelease", "ReleaseID")]
    // mConceptTranslation -> mLanguage
    [InlineData("mConceptTranslation", "LanguageID", "mLanguage", "LanguageID")]
    public void NoOrphanForeignKeys(string childTable, string childColumn, string parentTable, string parentColumn)
    {
        QueryHelpers.AssertNoOrphans(_fixture.GeneratedConnection, childTable, childColumn, parentTable, parentColumn);
    }

    // ------------------------------------------------------------------
    // 3. Hierarchy trees: no cycles, coherent Path/Level/ParentMemberID
    //
    // DictionaryLoader does NOT copy Path/Level/ParentMemberID verbatim from the Access. The
    // Access has 202 nodes out of 18,390 (7 hierarchies) where those three columns contradict
    // each other -and none is reliable in every case-, so the converter normalises: Path wins (it
    // is rebuilt from ParentMemberID only if it is malformed, that is, if it does not end in the
    // MemberID itself), and Level/ParentMemberID are ALWAYS DERIVED from the final Path (Level =
    // number of segments, ParentMemberID = second-to-last segment, NULL if there is only one). The
    // Path separator and terminator is the dot, never the comma (the EIOPA documentation says
    // "comma", but the data measured in the Access and in the three references uses the dot).
    //
    // Consequence: the three assertions of this section must hold with ZERO exceptions -- there
    // is no reference-defect exception to apply here, because the converter itself normalises the
    // source defect; it is not a defect of the reference.
    // ------------------------------------------------------------------

    private sealed record HierarchyNode(int HierarchyId, int MemberId, int? ParentMemberId, int Level, string? Path);

    /// <summary>
    /// Translates each segment (a <c>MemberID</c> as text) of a raw Access <c>Path</c> with
    /// <paramref name="renumbering"/>. Reimplemented here on purpose, instead of invoking the
    /// private namesake of <c>DictionaryLoader</c>: a test that calls the function it claims to
    /// test does not detect an error shared by both (same criterion as
    /// <c>ConceptReleaseTests.ExtractReleaseSuffix</c>).
    /// </summary>
    private static string? TranslateHierarchyNodePathMemberIds(string? path, MemberIdRenumbering renumbering)
    {
        if (string.IsNullOrEmpty(path))
        {
            return path;
        }

        var segments = path.Split('.', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(segments.Select(
            segment => renumbering.Translate(int.Parse(segment, CultureInfo.InvariantCulture)).ToString(CultureInfo.InvariantCulture) + "."));
    }

    private List<HierarchyNode> LoadHierarchyNodes()
    {
        var rows = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            "SELECT \"HierarchyID\", \"MemberID\", \"ParentMemberID\", \"Level\", \"Path\" FROM \"mHierarchyNode\"",
            5);

        return rows
            .Select(r => new HierarchyNode(
                int.Parse(r[0]!),
                int.Parse(r[1]!),
                r[2] is null ? null : int.Parse(r[2]!),
                int.Parse(r[3]!),
                r[4]))
            .ToList();
    }

    [DataFact]
    public void HierarchyTree_NoCycles()
    {
        var nodes = LoadHierarchyNodes();
        var byKey = nodes.ToDictionary(n => (n.HierarchyId, n.MemberId));

        var cyclesFound = new List<string>();

        foreach (var node in nodes)
        {
            var visited = new HashSet<(int, int)>();
            var current = node;

            while (current.ParentMemberId is { } parentId)
            {
                var key = (current.HierarchyId, current.MemberId);
                if (!visited.Add(key))
                {
                    cyclesFound.Add($"HierarchyID={node.HierarchyId}, MemberID={node.MemberId}");
                    break;
                }

                if (!byKey.TryGetValue((current.HierarchyId, parentId), out var parent))
                {
                    // Parent missing in the same hierarchy: the ParentMemberID -> mMember orphan
                    // test covers it, but here, without a parent row in mHierarchyNode, there is
                    // no cycle to chase; the check for this node is cut short.
                    break;
                }

                current = parent;
            }
        }

        Assert.True(
            cyclesFound.Count == 0,
            $"Cycles detected in the hierarchy tree: {string.Join("; ", cyclesFound.Take(10))}");
    }

    [DataFact]
    public void HierarchyTree_LevelIsParentLevelPlusOne()
    {
        // Level is derived from the final Path: this test must pass without exceptions. If it
        // failed again, it would be a real regression of the normalisation, not a source defect
        // (already corrected during loading).
        var nodes = LoadHierarchyNodes();
        var byKey = nodes.ToDictionary(n => (n.HierarchyId, n.MemberId));

        var mismatches = new List<string>();

        foreach (var node in nodes)
        {
            if (node.ParentMemberId is not { } parentId)
            {
                continue; // root: no parent to compare against.
            }

            if (!byKey.TryGetValue((node.HierarchyId, parentId), out var parent))
            {
                continue; // orphan, covered by another test
            }

            if (node.Level != parent.Level + 1)
            {
                mismatches.Add(
                    $"HierarchyID={node.HierarchyId} MemberID={node.MemberId} Level={node.Level} " +
                    $"vs ParentMemberID={parentId} Level={parent.Level}");
            }
        }

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} nodes with Level != Level(parent) + 1. Examples: " +
            string.Join("; ", mismatches.Take(10)));
    }

    [DataFact]
    public void HierarchyTree_PathEndsWithOwnMemberId_AndPrefixMatchesParentPath()
    {
        // Path separator and terminator: the dot (the EIOPA documentation says "comma", but the
        // data measured in the Access and in the three references prevails). This test must pass
        // without exceptions.
        var nodes = LoadHierarchyNodes();
        var byKey = nodes.ToDictionary(n => (n.HierarchyId, n.MemberId));

        var pathMismatches = new List<string>();
        var prefixMismatches = new List<string>();

        foreach (var node in nodes)
        {
            Assert.False(string.IsNullOrEmpty(node.Path), $"HierarchyID={node.HierarchyId} MemberID={node.MemberId}: null Path after normalisation (unexpected, one must always be produced).");

            var ownSegment = node.MemberId.ToString() + ".";
            if (!node.Path!.EndsWith(ownSegment, StringComparison.Ordinal))
            {
                pathMismatches.Add($"HierarchyID={node.HierarchyId} MemberID={node.MemberId} Path='{node.Path}'");
                continue;
            }

            if (node.ParentMemberId is not { } parentId)
            {
                if (node.Path != ownSegment)
                {
                    pathMismatches.Add(
                        $"HierarchyID={node.HierarchyId} MemberID={node.MemberId} (root): Path='{node.Path}' " +
                        $"different from its own segment '{ownSegment}'");
                }

                continue;
            }

            if (!byKey.TryGetValue((node.HierarchyId, parentId), out var parent) || parent.Path is null)
            {
                continue; // orphan or parent without Path, covered by other tests
            }

            var expectedPath = parent.Path + ownSegment;
            if (expectedPath != node.Path)
            {
                prefixMismatches.Add(
                    $"HierarchyID={node.HierarchyId} MemberID={node.MemberId} Path='{node.Path}' " +
                    $"vs expected (parent '{parent.Path}' + '{ownSegment}') = '{expectedPath}'");
            }
        }

        Assert.True(
            pathMismatches.Count == 0,
            $"{pathMismatches.Count} nodes whose Path does not end in their own MemberID (or, being " +
            $"a root, is not exactly that segment). Examples: " + string.Join("; ", pathMismatches.Take(10)));

        Assert.True(
            prefixMismatches.Count == 0,
            $"{prefixMismatches.Count} nodes whose Path does not extend that of their parent. Examples: " +
            string.Join("; ", prefixMismatches.Take(10)));
    }

    [DataFact]
    public void HierarchyTree_LevelEqualsPathSegmentCount()
    {
        // Explicit assertion: Level == number of segments of Path.
        var nodes = LoadHierarchyNodes();

        var mismatches = nodes
            .Where(n => !string.IsNullOrEmpty(n.Path))
            .Select(n => (Node: n, SegmentCount: n.Path!.Split('.', StringSplitOptions.RemoveEmptyEntries).Length))
            .Where(t => t.Node.Level != t.SegmentCount)
            .Select(t => $"HierarchyID={t.Node.HierarchyId} MemberID={t.Node.MemberId} Level={t.Node.Level} Path='{t.Node.Path}' (segments={t.SegmentCount})")
            .ToList();

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} nodes with a Level different from the number of Path segments. Examples: " +
            string.Join("; ", mismatches.Take(10)));
    }

    [DataFact]
    public void HierarchyTree_ParentMemberIdEqualsPenultimatePathSegment()
    {
        // Explicit assertion: ParentMemberID == second-to-last segment of Path (NULL if Path has
        // only one segment, that is, if the node is a root).
        var nodes = LoadHierarchyNodes();

        var mismatches = new List<string>();

        foreach (var node in nodes)
        {
            if (string.IsNullOrEmpty(node.Path))
            {
                continue; // covered by HierarchyTree_PathEndsWithOwnMemberId_...
            }

            var segments = node.Path.Split('.', StringSplitOptions.RemoveEmptyEntries);
            int? expectedParentId = segments.Length >= 2 ? int.Parse(segments[^2]) : null;

            if (node.ParentMemberId != expectedParentId)
            {
                mismatches.Add(
                    $"HierarchyID={node.HierarchyId} MemberID={node.MemberId} ParentMemberID={(node.ParentMemberId?.ToString() ?? "NULL")} " +
                    $"vs second-to-last segment of Path='{node.Path}' = {(expectedParentId?.ToString() ?? "NULL")}");
            }
        }

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} nodes with a ParentMemberID different from the second-to-last Path segment. Examples: " +
            string.Join("; ", mismatches.Take(10)));
    }

    /// <summary>
    /// Control figure of the normalisation: it must touch exactly 202 of the 18,390 nodes of the
    /// Access, spread over the 7 hierarchies 39178, 39179, 39180, 39181, 39183, 39186 and 47002.
    /// A node counts as "touched" if its generated <c>Path</c>, <c>Level</c> or
    /// <c>ParentMemberID</c> differ from those in the Access, AFTER applying the MemberID
    /// renumbering to it (<see cref="DictionaryFixture.DictionaryResult"/>.<c>MemberIdRenumbering</c>):
    /// the only affected occupant (<c>C27_12</c>, Access <c>MemberID</c> 9999) changes ID in the
    /// destination, so comparing against the untranslated Access verbatim would compare the wrong
    /// row (or none). If this figure changed (with the same Access), it would be a signal to
    /// escalate: either the normalisation stopped being stable, or the Access changed and the
    /// rule must be reviewed.
    /// </summary>
    [DataFact]
    public void HierarchyTree_Normalization_TouchesExactly202NodesInSevenHierarchies()
    {
        var renumbering = _fixture.DictionaryResult.MemberIdRenumbering;

        // The Access side is translated BEFORE indexing, with the same transformation that
        // DictionaryLoader.ApplyMemberIdRenumbering applies in production (MemberID,
        // ParentMemberID and each numeric segment of Path), so that the key and the values match
        // what is actually in mHierarchyNode.
        var accessByKey = _fixture.AccessReader.ReadHierarchyNodes()
            .ToDictionary(
                n => (n.HierarchyId, MemberId: renumbering.Translate(n.MemberId)),
                n => (
                    ParentMemberId: renumbering.TranslateNullable(n.ParentMemberId),
                    n.Level,
                    Path: TranslateHierarchyNodePathMemberIds(n.Path, renumbering)));

        var generatedRows = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            "SELECT \"HierarchyID\", \"MemberID\", \"ParentMemberID\", \"Level\", \"Path\" FROM \"mHierarchyNode\"",
            5);

        Assert.True(
            generatedRows.Count == accessByKey.Count,
            $"mHierarchyNode has {generatedRows.Count} generated rows versus {accessByKey.Count} " +
            "in Access.HierarchyNode: the normalisation comparison requires the same census.");

        var touchedHierarchyIds = new SortedSet<int>();
        var touchedCount = 0;

        foreach (var row in generatedRows)
        {
            var hierarchyId = int.Parse(row[0]!);
            var memberId = int.Parse(row[1]!);
            int? generatedParentMemberId = row[2] is null ? null : int.Parse(row[2]!);
            var generatedLevel = int.Parse(row[3]!);
            var generatedPath = row[4];

            var access = accessByKey[(hierarchyId, memberId)];

            var touched = access.Level != generatedLevel
                || access.ParentMemberId != generatedParentMemberId
                || access.Path != generatedPath;

            if (touched)
            {
                touchedCount++;
                touchedHierarchyIds.Add(hierarchyId);
            }
        }

        var expectedHierarchyIds = new SortedSet<int> { 39178, 39179, 39180, 39181, 39183, 39186, 47002 };

        Assert.True(
            touchedCount == 202,
            $"The normalisation touches {touchedCount} nodes (of {generatedRows.Count}); exactly " +
            $"202 were expected. Affected HierarchyID: [{string.Join(",", touchedHierarchyIds)}].");

        Assert.True(
            touchedHierarchyIds.SetEquals(expectedHierarchyIds),
            $"Hierarchies touched by the normalisation: [{string.Join(",", touchedHierarchyIds)}] " +
            $"versus the expected [{string.Join(",", expectedHierarchyIds)}].");
    }

    [DataFact]
    public void HierarchyTree_OrderIsUniquePerParent()
    {
        // Coherent Order: within the same (HierarchyID, ParentMemberID), there must not be two
        // siblings with the same Order (ambiguity of position).
        var rows = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            """
            SELECT "HierarchyID", "ParentMemberID", "Order", COUNT(*) AS Cnt
            FROM "mHierarchyNode"
            WHERE "ParentMemberID" IS NOT NULL
            GROUP BY "HierarchyID", "ParentMemberID", "Order"
            HAVING COUNT(*) > 1
            """,
            4);

        Assert.True(
            rows.Count == 0,
            $"{rows.Count} groups (HierarchyID, ParentMemberID, Order) with more than one sibling. " +
            $"Examples: {string.Join("; ", rows.Take(10).Select(r => string.Join(",", r)))}");
    }
}
