namespace EbaDpm.Converter.Tests.Dictionary;

/// <summary>
/// "Integrity" level over the template and table tree generated by
/// <c>TemplateOrTableLoader</c>: <c>mTemplateOrTable</c>, <c>mTable</c>, <c>mTaxonomyTable</c>.
/// Critical layer: these tests fail the build.
///
/// <c>ParentTemplateOrTableID = 0</c> is the root sentinel ("root with Parent = 0, not NULL"),
/// NOT an orphan: the <c>Level = 1</c>/<c>TableGroup</c> nodes always carry it, and the
/// references themselves follow the same pattern (4.0: 4,251 cases; 4.2: 158). It is excluded
/// from the orphan check; any other orphan does fail.
/// </summary>
[Collection("Dictionary")]
public sealed class TemplateOrTableIntegrityTests
{
    private readonly DictionaryFixture _fixture;

    public TemplateOrTableIntegrityTests(DictionaryFixture fixture)
    {
        _fixture = fixture;
    }

    // ------------------------------------------------------------------
    // 1. Informative counts
    // ------------------------------------------------------------------

    [DataFact]
    public void RowCounts_AreConsistentWithTheLoaderResult()
    {
        // Sanity check: what TemplateOrTableLoader.Load returns matches what is actually in the
        // generated database (not a tautology: the Result is computed separately from the
        // INSERTs, so a discrepancy would indicate a counting error).
        var templateOrTableCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, "SELECT COUNT(*) FROM \"mTemplateOrTable\"");
        var tableCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, "SELECT COUNT(*) FROM \"mTable\"");
        var taxonomyTableCount = QueryHelpers.Scalar(_fixture.GeneratedConnection, "SELECT COUNT(*) FROM \"mTaxonomyTable\"");

        Assert.Equal(_fixture.TemplateOrTableResult.TemplateOrTableRows, (int)templateOrTableCount);
        Assert.Equal(_fixture.TemplateOrTableResult.TableRows, (int)tableCount);
        Assert.Equal(_fixture.TemplateOrTableResult.TaxonomyTableRows, (int)taxonomyTableCount);

        Assert.True(templateOrTableCount > 0, "mTemplateOrTable is empty; nodes for COREP 3.2 were expected.");
        Assert.True(tableCount > 0, "mTable is empty; tables for COREP 3.2 were expected.");
        Assert.True(taxonomyTableCount > 0, "mTaxonomyTable is empty; links for COREP 3.2 were expected.");
    }

    // ------------------------------------------------------------------
    // 2. FKs without orphans, except for the Parent = 0 sentinel
    // ------------------------------------------------------------------

    [DataFact]
    public void TemplateOrTable_ParentId_HasNoOrphans_ExcludingTheRootSentinelZero()
    {
        var (orphanCount, samples) = QueryHelpers.FindOrphans(
            _fixture.GeneratedConnection, "mTemplateOrTable", "ParentTemplateOrTableID", "mTemplateOrTable", "TemplateOrTableID");

        // FindOrphans already excludes NULL; here the sentinel 0 must also be discounted, since
        // by definition there is no TemplateOrTableID=0 row and it would show up as an "orphan".
        var trueOrphanCount = QueryHelpers.Scalar(
            _fixture.GeneratedConnection,
            """
            SELECT COUNT(*) FROM "mTemplateOrTable" c
            WHERE c."ParentTemplateOrTableID" IS NOT NULL
              AND c."ParentTemplateOrTableID" <> 0
              AND NOT EXISTS (SELECT 1 FROM "mTemplateOrTable" p WHERE p."TemplateOrTableID" = c."ParentTemplateOrTableID")
            """);

        Assert.True(
            trueOrphanCount == 0,
            $"{trueOrphanCount} mTemplateOrTable rows with an orphaned ParentTemplateOrTableID " +
            $"(discounting the sentinel 0). Sample (includes the sentinel, ignore the '0'): {string.Join(", ", samples)}");
    }

    [DataFact]
    public void TemplateOrTable_Level1Nodes_AlwaysUseTheRootSentinelZero()
    {
        // Closes the previous point: every Level=1 (TableGroup) node must carry the sentinel 0,
        // never NULL nor a real ID. If this changed, excluding "Parent=0" from the orphan test
        // would stop being safe.
        var nonZeroRootParents = QueryHelpers.Scalar(
            _fixture.GeneratedConnection,
            """
            SELECT COUNT(*) FROM "mTemplateOrTable"
            WHERE "TemplateOrTableType" = 'TableGroup' AND "Level" = 1
              AND ("ParentTemplateOrTableID" IS NULL OR "ParentTemplateOrTableID" <> 0)
            """);

        Assert.True(nonZeroRootParents == 0, $"{nonZeroRootParents} L1 (TableGroup) nodes without the sentinel ParentTemplateOrTableID=0.");
    }

    [DataTheory]
    [InlineData("mTemplateOrTable", "TaxonomyID", "mTaxonomy", "TaxonomyID")]
    [InlineData("mTemplateOrTable", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mTable", "ConceptID", "mConcept", "ConceptID")]
    [InlineData("mTaxonomyTable", "TaxonomyID", "mTaxonomy", "TaxonomyID")]
    [InlineData("mTaxonomyTable", "TableID", "mTable", "TableID")]
    [InlineData("mTaxonomyTable", "AnnotatedTableID", "mTemplateOrTable", "TemplateOrTableID")]
    public void NoOrphanForeignKeys(string childTable, string childColumn, string parentTable, string parentColumn)
    {
        QueryHelpers.AssertNoOrphans(_fixture.GeneratedConnection, childTable, childColumn, parentTable, parentColumn);
    }

    // ------------------------------------------------------------------
    // 3. Coherent L2 -> L1 tree
    // ------------------------------------------------------------------

    [DataFact]
    public void Level2Nodes_HaveAnExistingLevel1Parent_OfType_TableGroup()
    {
        var mismatches = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            """
            SELECT c."TemplateOrTableID", c."TemplateOrTableCode", c."ParentTemplateOrTableID"
            FROM "mTemplateOrTable" c
            WHERE c."TemplateOrTableType" = 'TableGroup' AND c."Level" = 2
              AND NOT EXISTS (
                  SELECT 1 FROM "mTemplateOrTable" p
                  WHERE p."TemplateOrTableID" = c."ParentTemplateOrTableID"
                    AND p."TemplateOrTableType" = 'TableGroup' AND p."Level" = 1
              )
            """,
            3);

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} L2 nodes without a valid L1 (TableGroup) parent. Examples: " +
            string.Join("; ", mismatches.Take(10).Select(r => string.Join(",", r))));
    }

    [DataFact]
    public void Level2Nodes_ParentBelongsToTheSameTaxonomy()
    {
        // The parent of every L2 node belongs to its same taxonomy (the Access has not a single
        // crossed case in 6,136 TaxonomyTableVersion rows).
        var mismatches = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            """
            SELECT c."TemplateOrTableID", c."TaxonomyID", p."TaxonomyID"
            FROM "mTemplateOrTable" c
            JOIN "mTemplateOrTable" p ON p."TemplateOrTableID" = c."ParentTemplateOrTableID"
            WHERE c."TemplateOrTableType" = 'TableGroup' AND c."Level" = 2
              AND c."TaxonomyID" <> p."TaxonomyID"
            """,
            3);

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} L2 nodes whose L1 parent belongs to another taxonomy. Examples: " +
            string.Join("; ", mismatches.Take(10).Select(r => string.Join(",", r))));
    }

    [DataFact]
    public void BusinessTableNodes_WithNonZeroParent_HaveAnExistingLevel2Parent()
    {
        // The "0 if it does not resolve" documented in TemplateOrTableLoader is a legitimate
        // fallback, but IF a non-zero parent appears, it must be a real L2 node; no intermediate
        // third state is accepted.
        var mismatches = QueryHelpers.Rows(
            _fixture.GeneratedConnection,
            """
            SELECT c."TemplateOrTableID", c."TemplateOrTableCode", c."ParentTemplateOrTableID"
            FROM "mTemplateOrTable" c
            WHERE c."TemplateOrTableType" = 'BusinessTable' AND c."ParentTemplateOrTableID" <> 0
              AND NOT EXISTS (
                  SELECT 1 FROM "mTemplateOrTable" p
                  WHERE p."TemplateOrTableID" = c."ParentTemplateOrTableID"
                    AND p."TemplateOrTableType" = 'TableGroup' AND p."Level" = 2
              )
            """,
            3);

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count} BusinessTable nodes with a non-zero parent that is not a valid L2 node. Examples: " +
            string.Join("; ", mismatches.Take(10).Select(r => string.Join(",", r))));
    }

    [DataFact]
    public void BusinessTableNodes_NeverFallBackToTheRootSentinel_InThisRun()
    {
        // Not a structural guarantee (the loader itself documents the fallback to 0 as legitimate
        // if it does not resolve), but for COREP 3.2 the L2->L1 link through TaxonomyTableVersion
        // must always resolve: if a 0 appears here, it is a real regression to investigate, not
        // to silence.
        var fallbackCount = QueryHelpers.Scalar(
            _fixture.GeneratedConnection,
            "SELECT COUNT(*) FROM \"mTemplateOrTable\" WHERE \"TemplateOrTableType\" = 'BusinessTable' AND \"ParentTemplateOrTableID\" = 0");

        Assert.True(
            fallbackCount == 0,
            $"{fallbackCount} BusinessTable nodes with ParentTemplateOrTableID=0 (\"unresolved\" fallback) " +
            "in the COREP 3.2 reference run; full resolution was expected.");
    }
}
